import { Cidade } from '../dados';

const CIDADES_INICIAIS: Cidade[] = [
  {
    id: '1',
    nome: 'São Paulo',
    descricao: 'A maior metrópole do Brasil e um dos maiores centros financeiros e culturais da América Latina. Oferece gastronomia diversificada, museus de classe mundial, vida noturna vibrante e uma arquitetura que mescla o histórico com o ultramoderno.',
    categoria: 'Moderna',
    populacao: '12,3 milhões',
    pais: 'Brasil',
    entrada: 'Gratuito',
    latitude: '-23.5505',
    longitude: '-46.6333',
  },
  {
    id: '2',
    nome: 'Rio de Janeiro',
    descricao: 'Cidade Maravilhosa, famosa pelo Cristo Redentor, praias icônicas como Copacabana e Ipanema, o Carnaval mais famoso do mundo e o Pão de Açúcar. Uma das cidades mais belas do planeta.',
    categoria: 'Cultural',
    populacao: '6,7 milhões',
    pais: 'Brasil',
    entrada: 'Gratuito',
    latitude: '-22.9068',
    longitude: '-43.1729',
  },
  {
    id: '3',
    nome: 'Curitiba',
    descricao: 'Capital do Paraná, referência mundial em planejamento urbano e qualidade de vida. Conhecida pelos parques, pelo Jardim Botânico, pela Ópera de Arame e pelo sistema de transporte coletivo exemplar.',
    categoria: 'Moderna',
    populacao: '1,9 milhão',
    pais: 'Brasil',
    entrada: 'Gratuito',
    latitude: '-25.4284',
    longitude: '-49.2733',
  },
  {
    id: '4',
    nome: 'Salvador',
    descricao: 'Primeira capital do Brasil, Salvador é o coração da cultura afro-brasileira. O Pelourinho, Patrimônio da Humanidade, encanta com igrejas barrocas, capoeira nas ruas, música axé e culinária baiana única.',
    categoria: 'Histórica',
    populacao: '2,9 milhões',
    pais: 'Brasil',
    entrada: 'Gratuito',
    latitude: '-12.9714',
    longitude: '-38.5014',
  },
  {
    id: '5',
    nome: 'Florianópolis',
    descricao: 'A Ilha da Magia possui mais de 40 praias paradisíacas, trilhas, lagoas e uma infraestrutura turística completa. Capital catarinense com forte influência açoriana e crescente polo tecnológico.',
    categoria: 'Natureza',
    populacao: '516 mil',
    pais: 'Brasil',
    entrada: 'Gratuito',
    latitude: '-27.5954',
    longitude: '-48.5480',
  },
  {
    id: '6',
    nome: 'Buenos Aires',
    descricao: 'A Paris da América do Sul combina arquitetura europeia, tango, futebol apaixonado e gastronomia sofisticada. Bairros como Palermo e San Telmo misturam arte, design e boemia de forma inigualável.',
    categoria: 'Cultural',
    populacao: '3,1 milhões',
    pais: 'Argentina',
    entrada: 'Gratuito',
    latitude: '-34.6037',
    longitude: '-58.3816',
  },
  {
    id: '7',
    nome: 'Machu Picchu',
    descricao: 'Considerada uma das 7 Maravilhas do Mundo Moderno, a cidade inca perdida nas montanhas dos Andes peruanos é um destino histórico e espiritual único. Altitude de 2.430 m com paisagens deslumbrantes.',
    categoria: 'Histórica',
    populacao: '1,1 mil',
    pais: 'Peru',
    entrada: 'R$ 280',
    latitude: '-13.1631',
    longitude: '-72.5450',
  },
  {
    id: '8',
    nome: 'Santiago',
    descricao: 'Capital chilena situada entre os Andes e o oceano Pacífico. Oferece modernos centros financeiros, rica vida cultural, excelentes vinhos e fácil acesso ao esqui nas montanhas e às praias.',
    categoria: 'Moderna',
    populacao: '7,1 milhões',
    pais: 'Chile',
    entrada: 'Gratuito',
    latitude: '-33.4489',
    longitude: '-70.6693',
  },
  {
    id: '9',
    nome: 'Cartagena',
    descricao: 'Joia do Caribe colombiano, Cartagena encanta com sua cidade murada colorida, Patrimônio da Humanidade pela UNESCO. Praias cristalinas, fortalezas históricas e uma atmosfera colonial romântica incomparável.',
    categoria: 'Histórica',
    populacao: '1,0 milhão',
    pais: 'Colômbia',
    entrada: 'Gratuito',
    latitude: '10.3910',
    longitude: '-75.4794',
  },
  {
    id: '10',
    nome: 'Bonito',
    descricao: 'Capital do Ecoturismo, Bonito é famosa por rios de água cristalina, grutas, cachoeiras e rica fauna aquática. O turismo sustentável é modelo mundial, com snorkel em rios e mergulho em cavernas alagadas.',
    categoria: 'Natureza',
    populacao: '22 mil',
    pais: 'Brasil',
    entrada: 'R$ 120',
    latitude: '-21.1267',
    longitude: '-56.4836',
  },
];

// Banco GLOBAL — mesma instância compartilhada em todo o app
export let banco: Cidade[] = [...CIDADES_INICIAIS];
export let proximoId = CIDADES_INICIAIS.length + 1;

export const setBanco = (novas: Cidade[]) => { banco = novas; };
export const setProximoId = (id: number) => { proximoId = id; };
